title: "Connecting Stellar Chemistry to Exoplanet Structure and Atmospheres"
description: "CS23 splinter session â€” bridging host-star abundances with exoplanet interiors and atmospheric composition in the JWST/ARIEL era."

url: "https://souto.github.io"
baseurl: "/cs23-stellar-exoplanet-atmospheres"

remote_theme: just-the-docs/just-the-docs
just_the_docs:
  custom_css:
    - assets/css/just-the-docs-custom.scss


plugins:
  - jekyll-remote-theme

search_enabled: true
permalink: pretty
color_scheme: light
heading_anchors: true

aux_links:
  "Program":
    - "https://souto.github.io/cs23-stellar-exoplanet-atmospheres/program/"
  "Call for Contributions":
    - "https://souto.github.io/cs23-stellar-exoplanet-atmospheres/call-for-contributions/"
  "Contact":
    - "https://souto.github.io/cs23-stellar-exoplanet-atmospheres/contact/"
  "CS23 Main Website":
    - "https://coolstars23.github.io/"
