title: Connecting Cool Dwarfs' Stellar Chemistry to Exoplanet Structure and Atmospheres
description: The Cool Stars 23 webpage for the Connecting Cool Dwarfs' Stellar Chemistry to Exoplanet Structure and Atmospheres Splinter Session
theme: just-the-docs
color_scheme: light

url: 
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
